class WelcomeController < ApplicationController
	
  def index
  	@word1 = LWords.sample.capitalize
  	@word2 = LWords.sample.capitalize 
  	render plain: @word1 + " of " + @word2
  end
  
  
  
  
  
  LWords = %w(lab label labor laboratory laborer labour labyrinth lace lack lacquer lactate lad ladder ladle lady lag lagoon laity lake lamb lament laminate lamp lamplight lance land landau landing landlord landmark landscape landslide lane language lantern lanthanum lap lapel lapidary lapse larceny lard larder large largesse lark larkspur larvae lash lasso last latch latex lath lathe lather latitude lattice laudanum laugh laughter launch launcher launching laundering laundry laureate laurel lava lavatory lavender law lawmaking lawman lawmen lawn lawsuit lawyer laxative layer layette laying layman laymen layout lead leader leadership leadsman leaf leafhopper leaflet leafmold league leaguer leak leakage leap leapfrog learning lease leash least leasure leather leave leavening lebensraum lecher lecture lecturer ledge ledger leeway left leftfield lefthander leftist leg legacy legality legatee legation legato legend legibility legion legislation legislator legislature legitimacy legume leisure lemon lemonade lending length leprae leprosy lesion lessening lesson let lethality lethargy letter letterhead lettering letterman lettermen letting leukemia levee level leveling lever leverage levitation levity levy lexicon liability liaison liar libel liberal liberalism liberality liberation libertie libertine liberty libido librarian library libretto lice license licensee licensing lid lie lieder lien lieu lieutenant life lifeblood lifeboat lifer lifetime lift lifting ligament ligand light lighter lighting lightning lightweight lignite likelihood liking lilt limb limber limbo lime limelight limit limitation limousine limp linden line lineage lineback lineman linen liner lineup lingerie lingo linguist liniment link linkage linking linoleum lint lion lip lipstick liqueur liquid liquidation liquidity liquor lise list listener listing lit liter literalism literature lithograph litigant litigation litorigin litter litterbug livability livelihood liver livery livestock living load loader loading loaf loan loathing lobby lobe loblolly lobo lobscouse lobster lobularity lobule loc local locale locality localization location lock locker lockup locomotive locust lodge lodging lodgment loft log logarithm logger logging logic loin loincloth longevity longhand longhorn longing longitude longrun longshoremen longshot longtime look looking lookout lookup loom loon loop loophole loose loot lope loquacity lord lordship lore loser lot lotion loudspeaker lounge louse love lover lovering lovie low lowering loyalist loyalty lubricant lubrication lucidity luck lucy lug luggage lull lullaby lulu lumber lumen luminescence luminosity lummox lump lunation lunch luncheon lunchroom lunchtime lung lurch lure lust luster lustre lute luxuriance luxury lymph lymphoma lyric lyricism lyricist lyriist)
end
